export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  /** Нет организации для Host / tenant не разрешён */
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  INCORRECT_CURRENT_PASSWORD = 'INCORRECT_CURRENT_PASSWORD',
  SAME_PASSWORD = 'SAME_PASSWORD',
  TOKEN_INVALID = 'TOKEN_INVALID',

  // Bookings
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  BOOKING_FORBIDDEN = 'BOOKING_FORBIDDEN',
  BOOKING_CONFLICT = 'BOOKING_CONFLICT',
  BOOKING_DURATION_EXCEEDED = 'BOOKING_DURATION_EXCEEDED',
  RESOURCE_NOT_AVAILABLE = 'RESOURCE_NOT_AVAILABLE',

  // Users
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  CANNOT_MODIFY_SELF = 'CANNOT_MODIFY_SELF',
  INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',

  // Locations
  LOCATION_NOT_FOUND = 'LOCATION_NOT_FOUND',
  LOCATION_HAS_DEPENDENTS = 'LOCATION_HAS_DEPENDENTS',
  LOCATION_PARENT_NOT_FOUND = 'LOCATION_PARENT_NOT_FOUND',

  // Resources
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

  // Platform
  SLUG_TAKEN = 'SLUG_TAKEN',
  HOST_TAKEN = 'HOST_TAKEN',
  HOST_RESERVED = 'HOST_RESERVED',
  PLATFORM_ADMIN_EMAIL_AMBIGUOUS = 'PLATFORM_ADMIN_EMAIL_AMBIGUOUS',

  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
